[package]
name = "sbe_utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true
[dependencies]
common_errors = { workspace = true }
sbe_messages = {workspace = true}
